### ISSUE TITLE
Catch Exceptions

### ISSUE THREAD

**Issue by bokherus** [OOP2018/coinpurse-wisaTong#10]
In ConsoleDialog, you should use try-catch to catch the exception thrown from MoneyFactory when the value is not available in that currency. This allows the user to continue depositing with a valid value.

**Comment by wisaTong** [comment]
Fixed, I think?

**Comment by bokherus** [comment]
Not yet. You returned null, don't forget to deal with it.

<img width="502" alt="screen shot 2561-02-23 at 1 32 18 pm" src="https://user-images.githubusercontent.com/9125776/36581130-0adfd8ce-189e-11e8-9599-b678d3079d7d.png">
<img width="500" alt="screen shot 2561-02-23 at 1 32 32 pm" src="https://user-images.githubusercontent.com/9125776/36581132-0e15c3a0-189e-11e8-9f36-3ade40192e1b.png">

**Comment by wisaTong** [comment]
This time definitely fixed
