### ISSUE TITLE
Logic Improvement

### ISSUE THREAD

**Issue by bokherus** [OOP2018/coinpurse-wisaTong#12]
https://github.com/OOP2018/coinpurse-wisaTong/blob/2c469ad89f402da9df449d199adf10ee212f5901/src/factory/ThaiMoneyFactory.java#L29-L36

You can directly use
`return new BankNote(value, currency, serial++); `

Note:
`serial++` means use the value then increment it.
`++serial` means increment it then use the value.

**Comment by wisaTong** [comment]
Improved
