### ISSUE TITLE
== for String comparison

### ISSUE THREAD

**Issue by kykungz** [OOP2018/coinpurse-wisaTong#4]
You should use `equals()` method to check for String's equality. `==` is for checking the instance of Object, sometimes 2 Strings may have the same value, but are different Objects.
https://github.com/OOP2018/coinpurse-wisaTong/blob/fa9de7811087ca4b04706c9606680ae582d2eaf6/src/coinpurse/Coin.java#L57

**Comment by wisaTong** [comment]
Fixed
