### ISSUE TITLE
Coin should not be mentioned in Purse

### ISSUE THREAD

**Issue by chinnonae** [OOP2018/coinpurse-wisaTong#5]
As we enable Purse to accept more monetary objects, Coins should not be mentioned in Purse. Because Coins are not the only thing that can be put in the Purse.

![image](https://user-images.githubusercontent.com/11190475/35895317-81fafd2e-0be9-11e8-8ab1-eea697328050.png)

https://github.com/OOP2018/coinpurse-wisaTong/blob/8fdb6fa3f5282eba0659f73cca7bcc77f57b01db/src/coinpurse/Purse.java#L28-L31

**Comment by wisaTong** [comment]
Fixed
