### ISSUE TITLE
Logical Error in ValueComparator

### ISSUE THREAD

**Issue by chinnonae** [OOP2018/coinpurse-wisaTong#6]
The values are compared only when currencies are the same. If the currencies are different, you have to compare them instead.

![image](https://user-images.githubusercontent.com/11190475/35895717-3b86e248-0beb-11e8-8b5a-d405991a62f4.png)

https://github.com/OOP2018/coinpurse-wisaTong/blob/8fdb6fa3f5282eba0659f73cca7bcc77f57b01db/src/coinpurse/ValueComparator.java#L8-L12

**Comment by wisaTong** [comment]
Fixed
